server:
  port: 8080

eureka:
  client:
    register-with-eureka:false

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: estudiante
          uri: http://localhost:8090
          predicates:
            - Path=/microservice/cliente/**
        - id: profesores
          uri: http://localhost:8190
          predicates:
            - Path=/microservice/profesor/**
        - id: cursos
          uri: http://localhost:9090
          predicates:
            - Path=/microservice/curso/**